apiVersion: v1
kind: Service
metadata:
  name: api-wards
  labels:
    app: api-wards
spec:
  type: NodePort
  selector:
    app: api-wards
  ports:
  - protocol: "TCP"
    name: http
    port: 8080
    targetPort: 8080
